version: '3.8'

services: 

  rabbitmq:
    image: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'

  base:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - firebase_config
        - service_account
    volumes:
      - ./base:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    secrets:
      - firebase_config
      - service_account

  order_service:
    build:
      context: .
      dockerfile: api/order/Dockerfile
    volumes:
      - ./order:/app/api/order
    ports:
      - "5001:5001"
    env_file:
      - .env

  inventory_service:
    build:
      context: .
      dockerfile: api/inventory/Dockerfile
    volumes:
      - ./inventory:/app/api/inventory
    env_file:
      - .env

secrets:
  firebase_config:
    file: ./secret/firebase_config.py 
  service_account:
    file: ./secret/serviceAccount.json