"""Create order and inventory

Revision ID: 30009dcd684b
Revises: aaa4cdc85574
Create Date: 2024-06-19 19:18:17.768822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30009dcd684b'
down_revision = 'aaa4cdc85574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('stock_quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_quantity', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
