"""Update orders table

Revision ID: 3723731d36fd
Revises: fab3c9c434ef
Create Date: 2024-06-20 20:06:57.477889

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3723731d36fd'
down_revision = 'fab3c9c434ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('pending', 'processing', 'completed', 'cancelled', name='status'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('pending', 'processing', 'completed', 'cancelled', name='status'),
               nullable=True)

    # ### end Alembic commands ###
