"""Update books table

Revision ID: aaa4cdc85574
Revises: 46c9c367c390
Create Date: 2024-06-19 00:39:05.125222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa4cdc85574'
down_revision = '46c9c367c390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.UUID(), nullable=False))
        batch_op.drop_constraint('books_author_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('books_author_id_fkey', 'users', ['author_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('author_name')

    # ### end Alembic commands ###
